# Generated by Django 5.2.3 on 2026-08-13 06:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_on', models.DateField(default=django.utils.timezone.localdate, help_text='一覧では新しい順に並びます。', verbose_name='掲載日')),
                ('text', models.CharField(help_text='TOP に1行で表示されます。', max_length=200, verbose_name='本文')),
                ('badge', models.CharField(blank=True, help_text='右端に出る小さなラベル（例: イベント / GitHub）。空欄なら表示しません。', max_length=20, verbose_name='バッジ')),
                ('is_new', models.BooleanField(default=False, help_text='バッジの代わりに NEW を強調表示します。', verbose_name='NEW を付ける')),
                ('is_published', models.BooleanField(default=True, help_text='外すと下書き扱いになり、TOP には出ません。', verbose_name='公開する')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'お知らせ',
                'verbose_name_plural': 'お知らせ',
                'db_table': 'funitclub_news',
                'ordering': ['-published_on', '-id'],
            },
        ),
    ]
