# Generated by Django 5.2.3 on 2026-08-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('date', models.DateField(verbose_name='日付')),
                ('memo', models.TextField(blank=True, max_length=300, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'カウント対象',
                'verbose_name_plural': 'カウント対象',
                'db_table': 'funitclub_countevent',
                'ordering': ['date'],
            },
        ),
    ]
