# Generated by Django 5.2.3 on 2026-10-09 13:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_-]{3,30}$', 'ID は半角の英小文字・数字・「_」「-」で、3〜30文字にしてください。')], verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'カウント ID',
                'verbose_name_plural': 'カウント ID',
                'db_table': 'funitclub_countboard',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='countevent',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='countdown.board', verbose_name='ID'),
        ),
    ]
