# Generated by Django 5.2.3 on 2026-10-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0002_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='notified_on',
            field=models.DateField(blank=True, null=True, verbose_name='最後に通知した日'),
        ),
        migrations.AddField(
            model_name='board',
            name='notify_email_enc',
            field=models.TextField(blank=True, editable=False, verbose_name='通知先（暗号化）'),
        ),
        migrations.AddField(
            model_name='countevent',
            name='notify',
            field=models.BooleanField(default=False, verbose_name='メールで知らせる'),
        ),
    ]
