# Generated by Django 5.2.3 on 2026-08-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='メールの宛名や管理画面の表示に使います（例: 事務局）。', max_length=60, verbose_name='名前')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('receives_notifications', models.BooleanField(default=True, help_text='参加申し込み・IP遮断・エラーなどの通知メールが届きます。', verbose_name='通知を受け取る')),
                ('is_public_contact', models.BooleanField(default=True, help_text='アクセス制限の画面などに連絡先として表示されます。', verbose_name='公開ページの問い合わせ先にする')),
                ('is_active', models.BooleanField(default=True, help_text='外すと通知も表示もされなくなります（記録は残ります）。', verbose_name='有効')),
                ('sort_order', models.IntegerField(default=0, help_text='小さいほど先に使われます。問い合わせ先は先頭の1件を出します。', verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '管理者',
                'verbose_name_plural': '管理者',
                'db_table': 'funitclub_administrator',
                'ordering': ['sort_order', 'email'],
            },
        ),
    ]
