# Generated by Django 5.2.3 on 2026-08-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IPアドレス')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='理由')),
                ('block_count', models.PositiveIntegerField(default=1, help_text='繰り返すほど遮断期間が延びます。', verbose_name='遮断回数')),
                ('expires_at', models.DateTimeField(blank=True, help_text='空欄なら恒久遮断（解除するまで続きます）。', null=True, verbose_name='解除予定')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='初回遮断日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終遮断日時')),
            ],
            options={
                'verbose_name': '遮断IP',
                'verbose_name_plural': '遮断IP',
                'db_table': 'funitclub_blocked_ip',
                'ordering': ['-updated_at'],
            },
        ),
    ]
