# Generated by Django 5.2.3 on 2026-08-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='カードの上に出る番号（例: WG-01）。', max_length=20, verbose_name='識別子')),
                ('name', models.CharField(max_length=60, verbose_name='名前')),
                ('description', models.TextField(help_text='カードの本文。2〜3行くらい。', max_length=300, verbose_name='説明')),
                ('status', models.CharField(choices=[('active', '活動中'), ('idle', '準備中')], default='active', help_text='「活動中」だけが TOP の「活動中のWG」件数に入ります。「準備中」のカードには参加ボタンだけを出します。', max_length=10, verbose_name='状態')),
                ('app_url', models.URLField(blank=True, help_text='空欄なら「作成中」ページに繋ぎます（活動中のWGのみ表示）。', verbose_name='Webアプリの URL')),
                ('link_label', models.CharField(blank=True, help_text='2つ目のボタン（例: GitHub / 成果物レポート）。空欄なら出しません。', max_length=20, verbose_name='追加リンクの名前')),
                ('link_url', models.URLField(blank=True, help_text='空欄なら「作成中」ページに繋ぎます。', verbose_name='追加リンクの URL')),
                ('sort_order', models.IntegerField(default=0, help_text='小さいほど先に出ます。同じ値なら識別子順。', verbose_name='表示順')),
                ('is_published', models.BooleanField(default=True, help_text='外すと下書き扱いになり、WG一覧にも件数にも出ません。', verbose_name='公開する')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'WG',
                'verbose_name_plural': 'WG',
                'db_table': 'funitclub_wg',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='カードの上に出る分類（例: Web App / Model + API / Notebook）。', max_length=30, verbose_name='種別')),
                ('title', models.CharField(max_length=60, verbose_name='題名')),
                ('description', models.TextField(help_text='カードの本文。2〜3行くらい。', max_length=300, verbose_name='説明')),
                ('license', models.CharField(blank=True, help_text='カード右下のラベル（例: MIT / CC BY）。空欄なら出しません。', max_length=20, verbose_name='ライセンス')),
                ('url', models.URLField(blank=True, help_text='空欄なら「作成中」ページに繋ぎます。', verbose_name='公開先の URL')),
                ('sort_order', models.IntegerField(default=0, help_text='小さいほど先に出ます。同じ値なら新しい順。', verbose_name='表示順')),
                ('is_published', models.BooleanField(default=True, help_text='外すと下書き扱いになり、成果物一覧にも件数にも出ません。', verbose_name='公開する')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '成果物',
                'verbose_name_plural': '成果物',
                'db_table': 'funitclub_work',
                'ordering': ['sort_order', '-id'],
            },
        ),
    ]
