# Generated by Django 5.2.3 on 2026-09-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wg',
            name='github_team',
            field=models.CharField(blank=True, help_text='「WG に参加」で登録する WG のチームの名前（例: wg-countdown）。wg- で始まるものだけ。空欄なら「WG に参加」を出さない。', max_length=100, verbose_name='GitHub のチーム'),
        ),
    ]
